### PR TITLE
Show burn speed information during write

### PR DESCRIPTION
**Pull request by jviotti**
screenshot 2016-01-01 17 19 26

Fixes https://github.com/resin-io/resin-etcher/issues/89

### CODE REVIEW

**Comment by jviotti** [comment]
Needs discussion regarding the position of the speed text. Alternative:

screenshot 2016-01-01 17 27 10

**Comment by jviotti** [comment]
Works in OS X.

**Comment by jviotti** [comment]
Tested on Windows.

**Comment by taahirisaacs** [comment]
@jviotti prefer the burn speed outside the button. ie below the button.

**Comment by jviotti** [comment]
screenshot 2016-01-18 14 35 15

**Pull request merged**
